# Cas pratique en Python

## Devenons botanistes avec du machine learning

L'idée de cet exercice est de **classer** des iris par espèce en fonction de leur **caractéristiques**.

Nous pouvons faire cet exemple car nous avons à notre disposition un **jeu de données** sur 150 iris qui sont classées par espèces.

Nous avons les données suivantes pour chaque fleur :

- Longueur du pétale (cm)
- Largeur du pétale (cm)
- Longueur du sépale (cm)
- Largeur du sépale (cm)

Nous avons aussi pour chaque fleur son espèce.

Grâce à ces données, nous pouvons entraîner notre machine à **apprendre** et à **reconnaître** d'éventuelles futures iris !

Cet exemple est largement inspiré de l'article [initiation au machine learning avec Python](https://makina-corpus.com/blog/metier/2017/initiation-au-machine-learning-avec-python-pratique)

## Visualisons nos données

### Chargement


In [1]:
# On utilise la librairie scikit learn pour le machine learning
from sklearn import datasets

# On charge des données de test
iris = datasets.load_iris()

### Affichage des caractéristiques

On affiche quelque chose en Python avec la fonction `print()`.

Les caractéristiques sont disponibles dans l'attribut `feature_names` de l'objet `iris` ==> `iris.feature_names`.

In [2]:
# Affichage des caractéristiques des mesures
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


### Affichage des premières mesures

Les mesures sont disponibles dans l'attribut `data` de l'objet `iris` ==> `iris.data`.

L'attribut `data` est un tableau. Pour accéder aux 10 premières mesures, d'un tableau nommé `mon_tableau` on peut utiliser la notation suivante : `mon_tableau[0:10]`.

In [3]:
# Affichage des 5 premières mesures
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Affichage des espèces de fleurs

Les différentes espèces de fleurs sont disponibles dans l'attribut `target_names` de l'objet `iris` ==> `iris.target_names`.

In [4]:
# Affichage des classes de fleurs
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


### Affichage des classifications des fleurs

In [5]:
# Affichage des classifications
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Affichage de graphique représentant les données

In [6]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

data = iris.data

fig = plt.figure(figsize=(15, 7))
fig.subplots_adjust(hspace=0.4, wspace=0.4)
ax1 = plt.subplot(1,2,1)

clist = ['red', 'orange', 'blue']
colors = [clist[c] for c in iris.target]

ax1.scatter(data[:, 0], data[:, 1], c=colors)
plt.xlabel('Longueur du sépale (cm)')
plt.ylabel('Largueur du sépale (cm)')

ax2 = plt.subplot(1,2,2)

ax2.scatter(data[:, 2], data[:, 3], color=colors)

plt.xlabel('Longueur du pétale (cm)')
plt.ylabel('Largueur du pétale (cm)')

# Légende
for ind, s in enumerate(iris.target_names):
    # on dessine de faux points, car la légende n'affiche que les points ayant un label
    plt.scatter([], [], label=s, color=clist[ind])

plt.legend(scatterpoints=1, frameon=False, labelspacing=1
           , bbox_to_anchor=(1.8, .5) , loc="center right", title='Espèces')
plt.plot();